travis:
  secure:
    BINSTAR_TOKEN: HYNCOR4+azm8U2H3qlupBhq2gGKvvhzpbyQpNwUvv4uPfaG60yNm7EdEKuYX7BK0oaobjKQf/wyQb14yJDMIfwMLGWuTUnZTV24zPRi5RV61wDCceiW+76kB4Q/ttGXAosBN9sMySS7DQN9TLkY1d9Oe/N3m0XVW8BMKLQd4fRSV4iUaFdroKwRNtdzCwqEg9GZcPdpdyDufqzILepM6FeKn2ISevqZnoaQx8IuWjR4/drBfR2iklBjDkEBaGMQ6JHi7me2fU0EyNCHVxw6ZNtJbBE37tcZFZvo0ik5jy9bG6u5vaxXFxLWnL+Dd0QrOks06889DRbc61SH45TICjv7K1V2dgfm6vjy7KRoy/GngKsWTrvNzmZUqnzOzixft4Y6nzmsvlRvtuLLXueIzhTaWoG7zXb99sRzFbOjo8MypfQIpGucjI4azeMsWduG/KJOkS+zHkAlGH100eAu4pX08LaLIXlyKwOi1HT3pSh+VikKT4UnKBpBhaiLH2YVenqtkgIjbcduFJIkyeOdewY/Izi5tYXu5/bPi167ia0VtvH3dALvYxCi3QmycRYi+KGz42wzrzY+98uO6a8Il+snqhLFin2hwdtg5KqfxZ6pUDy0lsWFmGDn/UchWxV9q6od+bG2r9JePLUBnW83TO4Ee8kzXz57ySzUPMZjuM6Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
